name: CI
on: [ push, pull_request ]

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.4.0
      - uses: actions/setup-node@v2.1.4
        with:
          node-version: 15
      - run: npm install
      - run: npm run build --if-present
  Lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.4.0
      - uses: actions/setup-node@v2.1.4
      - run: npm install
      - run: npm run build --if-present 
      - run: npm run lint --if-present
